### ISSUE TITLE
DashBoard Schema.

### ISSUE THREAD

**Issue by Flustered** [Octophin/scute#1]
We need a way to control the overall look and layout of the device portal.

Suggested contents of dashboardSchema.json:

{
    "branding": {
        "siteName": "Horizon Portal",
        "siteLogo": "theLogo.svg"
    },
    "colours": {
        "mainColour": "#111111",
        "highlightColour": "#222222"
    },
    "mainNavigation": [
        {
            "title": "Device Manager",
            "route": "/"
        },
        {
            "title": "Preset Manager",
            "route": "/presets"
        },
        {
            "title": "Visualisations",
            "route": "/visuals"
        }
    ]
}

[dashboardSchema.zip](https://github.com/Octophin/scute/files/3397001/dashboardSchema.zip)

**Comment by FilipNest** [comment]
Following #6 we'll have `register_template_vars` and `options` passed in. I think options for logo etc. Titles etc can be overriden with the register_template_vars hook or such. Or even passed into an area of options as it's a dict so can take nested stuff.

I think we can probably close this one after that is in as it'll allow all sorts of extra templating functionality.
